# Pipeline Parameters
pipeline_params: {
    camera_balance: True,
    camera_proportion: "2-1",
    aerial_densify: True, 
    street_densify: False,
    weed_ratio: 0.0,
    add_prefilter: True,
    vis_step: 5000,
    no_prefilter_step: 0
}

# Optimization Parameters
optim_params: {
    iterations: 60000,
    position_lr_init: 0.0,
    position_lr_final: 0.0,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 60000,
    
    offset_lr_init: 0.001,
    offset_lr_final: 0.00001,
    offset_lr_delay_mult: 0.01,
    offset_lr_max_steps: 60000,

    feature_lr: 0.0075,
    scaling_lr: 0.007,
    rotation_lr: 0.002,
    
    mlp_opacity_lr_init: 0.002,
    mlp_opacity_lr_final: 0.00002,  
    mlp_opacity_lr_delay_mult: 0.01,
    mlp_opacity_lr_max_steps: 60000,

    mlp_cov_lr_init: 0.004,
    mlp_cov_lr_final: 0.004,
    mlp_cov_lr_delay_mult: 0.01,
    mlp_cov_lr_max_steps: 60000,
    
    mlp_color_lr_init: 0.008,
    mlp_color_lr_final: 0.00005,
    mlp_color_lr_delay_mult: 0.01,
    mlp_color_lr_max_steps: 60000,

    appearance_lr_init: 0.0,
    appearance_lr_final: 0.0,
    appearance_lr_delay_mult: 0.01,
    appearance_lr_max_steps: 60000,

    lambda_dssim: 0.2,
    lambda_dreg: 0.01,
    lambda_sky_opa: 0.05,
    lambda_opacity_entropy: 0.05,
    
    lambda_normal: 0.0,
    normal_start_iter: 7_000,
    lambda_dist: 0.0,
    dist_start_iter: 3_000,
    
    start_stat: 500,
    update_from: 1500,
    update_interval: 100,
    update_until: 30000,
    overlap: False,
    densification: True,

    growing_type: "mean",
    pruning_type: "mean",

    min_opacity: 0.005,
    success_threshold: 0.8,
    densify_grad_threshold: 0.0002,
    update_ratio: 0.2,
    extra_ratio: 0.25,
    extra_up: 0.05,
    start_depth: 500, # to avoid inf
    depth_l1_weight_init: 1.0,
    depth_l1_weight_final: 0.01,
}