data_params: {
    model_config: {
        name: "GaussianLoDModel",
        kwargs: {
            fork: 2,
            gs_attr: "2D",
            color_attr: "RGB",
            feat_dim: 32,
            view_dim: 3,
            appearance_dim: 0,
            n_offsets: 10, 
            voxel_size: 0.001,
            render_mode: "RGB+ED",
        }
    },
    source_path: "data/synthetic/citysample",
    pp_opt_yaml_path: "config/base/small_scene",  
    dataset_name: "horizongs_2d",
    scene_name: "synthetic/citysample", 
    images: "images",
    resolution: -1,
    white_background: False,
    random_background: False,
    resolution_scales: [1.0],
    data_device: "cpu",
    eval: True,
    ratio: 1,
    data_format: "city", #blender
    add_mask: True,
    add_depth: True,
    add_aerial: True,
    add_street: True,
    aerial_lod: "multi",
    street_lod: "multi",
    dist_ratio: 0.999,
    partition: False,
    scale: 0.25,
    center: [0,0,0],
    llffhold: 32,
}